# This is a basic workflow to help you get started with Actions

name: Download file from morph.io

on: repository_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Download the latest file from morph.io
    - name: Download CSV from morph.io
      run: wget https://morph.io/metaodi/covid-19-scraper-canton-be/data.csv?key=${{ secrets.MORPH_KEY }}&query=select+%2A+from+%22data%22 -O COVID19_Fallzahlen_Kanton_BE_total.csv

    # Commit to repo with updated file
    # copied from https://github.community/t5/GitHub-Actions/how-does-one-commit-from-an-action/m-p/31898/highlight/true#M934
    - name: Commit to repo with updated file
      run: |
          git add .
          git config --local user.email "odi@gha"
          git config --local user.name "GHA"
          git commit -a -m "Update COVID19_Fallzahlen_Kanton_BE_total.csv"
          git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
          eval `ssh-agent -t 60 -s`
          echo "$GHA_DEPLOY_KEY" | ssh-add -
          mkdir -p ~/.ssh/
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git push
          ssh-agent -k
